### ISSUE TITLE
Backend / admin

### ISSUE THREAD

**Issue by taufiq-46** [kinoarizu/shuseki#3]
Kalo mau jadi admin caranya gmn. Kok gak ada pilihannya atau layar adminnya untuk mengelola lokasi, qrcode, nama karyawan, dll

**Comment by kinoarizu** [comment]
halo mas @taufiq-46 , untuk akses akun adminnya sudah dibuatkan. Silahkan cek dokumentasi readme.md yang sudah dibuat.
